### ISSUE TITLE
Error occurred when I perform make operation

### ISSUE THREAD

**Issue by greendow** [dj-on-github/genrandom#2]
Thank you for sharing your codes on GitHub !
I use 64-bit CentOS 6.9. Gcc version is 4.4.7.  I met an error when performing make operation as follows:
make
gcc -c -I/usr/local/include -m64 -g -Wall -maes -o rdrand.o rdrand.c
rdrand.c: Assembler messages:
rdrand.c:222: Error: no such instruction: 'rdseed %ax'
rdrand.c:257: Error: no such instruction: 'rdseed %eax'
rdrand.c:292: Error: no such instruction: 'rdseed %rax'
make: *** [rdrand.o] Error 1
  Would you mind telling me how to solve this problem? Thank you in advance!

**Comment by dj-on-github** [comment]
That's gcc not having rdrand support. I'll go check the versions.

**Comment by dj-on-github** [comment]
RdRand support was introduced in GCC 4.6 in 2010.
RdSeed support came later. Looking for it. I'm using 5.3.1 and it's all there.

**Comment by dj-on-github** [comment]
The GCC website makes it hard to find when a feature was introduced. The patches came out in December 2014 for broadwell (which was the first CPU to have RdSeed). https://www.phoronix.com/scan.php?page=news_item&px=MTU0Nzc

**Comment by greendow** [comment]
Compilation errors result from the version of GCC. Thank you for pointing out this!
