### ISSUE TITLE
Cannot output random numbers

### ISSUE THREAD

**Issue by zhliao** [dj-on-github/genrandom#3]
Hi,

I tried to do the NIST randomnes test and have downloaded the source file and compiled it using the makefile. When I type the command:
./djenrandom -b -k 128 > megabitrand.bin

The system outputs an error:

Failed to open YAML output file  for writing
: No such file or directory

I am not sure if there any thing worng. Could you give me any advice? Thanks

**Comment by dj-on-github** [comment]
See number #18. It's was an uninitialized variable error. Update and recompile djenrandom.
